import { Achievement } from '@/src/types/achievement.types';

// config/achievements.config.ts
export const ACHIEVEMENT_DEFINITIONS: Omit<
  Achievement,
  'unlockedAt' | 'isUnlocked'
>[] = [
  // Pages Milestones
  {
    id: 'first_page',
    title: 'First Steps',
    description: 'Read your first page',
    icon: '📖',
    category: 'pages',
    requirement: 1,
    points: 10,
  },
  {
    id: 'century_reader',
    title: 'Century Reader',
    description: 'Read 100 pages',
    icon: '💯',
    category: 'pages',
    requirement: 100,
    points: 50,
  },
  {
    id: 'half_thousand',
    title: 'Half Thousand',
    description: 'Read 500 pages',
    icon: '📚',
    category: 'pages',
    requirement: 500,
    points: 100,
  },
  {
    id: 'thousand_pages',
    title: 'Millennium Reader',
    description: 'Read 1,000 pages',
    icon: '🎯',
    category: 'pages',
    requirement: 1000,
    points: 200,
  },
  {
    id: 'five_thousand',
    title: 'Bookworm',
    description: 'Read 5,000 pages',
    icon: '🐛',
    category: 'pages',
    requirement: 5000,
    points: 500,
  },
  {
    id: 'ten_thousand',
    title: 'Literary Legend',
    description: 'Read 10,000 pages',
    icon: '👑',
    category: 'pages',
    requirement: 10000,
    points: 1000,
  },

  // Books Completed
  {
    id: 'first_book',
    title: 'First Finish',
    description: 'Complete your first book',
    icon: '🏆',
    category: 'books',
    requirement: 1,
    points: 100,
  },
  {
    id: 'five_books',
    title: 'Avid Reader',
    description: 'Complete 5 books',
    icon: '📕',
    category: 'books',
    requirement: 5,
    points: 250,
  },
  {
    id: 'ten_books',
    title: 'Book Collector',
    description: 'Complete 10 books',
    icon: '📗',
    category: 'books',
    requirement: 10,
    points: 500,
  },
  {
    id: 'twenty_five_books',
    title: 'Library Builder',
    description: 'Complete 25 books',
    icon: '📘',
    category: 'books',
    requirement: 25,
    points: 1000,
  },
  {
    id: 'fifty_books',
    title: 'Master Reader',
    description: 'Complete 50 books',
    icon: '🎓',
    category: 'books',
    requirement: 50,
    points: 2000,
  },

  // Reading Streaks
  {
    id: 'three_day_streak',
    title: 'Habit Former',
    description: 'Read for 3 days in a row',
    icon: '🔥',
    category: 'streak',
    requirement: 3,
    points: 50,
  },
  {
    id: 'week_streak',
    title: 'Weekly Warrior',
    description: 'Read for 7 days in a row',
    icon: '⚡',
    category: 'streak',
    requirement: 7,
    points: 100,
  },
  {
    id: 'two_week_streak',
    title: 'Fortnight Fighter',
    description: 'Read for 14 days in a row',
    icon: '💪',
    category: 'streak',
    requirement: 14,
    points: 200,
  },
  {
    id: 'month_streak',
    title: 'Monthly Master',
    description: 'Read for 30 days in a row',
    icon: '🌟',
    category: 'streak',
    requirement: 30,
    points: 500,
  },
  {
    id: 'hundred_day_streak',
    title: 'Centurion',
    description: 'Read for 100 days in a row',
    icon: '💎',
    category: 'streak',
    requirement: 100,
    points: 1500,
  },

  // Reading Time
  {
    id: 'first_hour',
    title: 'Time Traveler',
    description: 'Read for 60 minutes total',
    icon: '⏰',
    category: 'time',
    requirement: 60,
    points: 25,
  },
  {
    id: 'ten_hours',
    title: 'Dedicated Reader',
    description: 'Read for 10 hours total',
    icon: '⌚',
    category: 'time',
    requirement: 600,
    points: 100,
  },
  {
    id: 'fifty_hours',
    title: 'Time Invested',
    description: 'Read for 50 hours total',
    icon: '🕐',
    category: 'time',
    requirement: 3000,
    points: 500,
  },
  {
    id: 'hundred_hours',
    title: 'Chronophile',
    description: 'Read for 100 hours total',
    icon: '⏳',
    category: 'time',
    requirement: 6000,
    points: 1000,
  },

  // Speed Reading
  {
    id: 'week_book',
    title: 'Speed Reader',
    description: 'Complete a book in 7 days',
    icon: '⚡',
    category: 'speed',
    requirement: 7,
    points: 150,
  },
  {
    id: 'three_day_book',
    title: 'Lightning Reader',
    description: 'Complete a book in 3 days',
    icon: '⚡⚡',
    category: 'speed',
    requirement: 3,
    points: 300,
  },
  {
    id: 'one_day_book',
    title: 'Marathon Reader',
    description: 'Complete a book in 1 day',
    icon: '🏃',
    category: 'speed',
    requirement: 1,
    points: 500,
  },
];
